---
# Set up apache vhosts
- name: Copy virtual host setup over
  template: src=vhost.conf dest=/etc/apache2/sites-available/
  sudo: yes
  
# Set username and group for apache to be the vagrant user's
- name: Copy Apache envars
  template: src=envvars dest=/etc/apache2/
  sudo: yes

# Add our vhosts and turn off the default one
- name: Activate virtual host
  command: a2ensite vhost
  notify: Restart webserver
  sudo: yes
  
- name: disable default virtual host
  command: a2dissite 000-default
  notify: Restart apache
  sudo: yes
